spring:
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: classpath:import-data.sql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        database: ORACLE
        database-platform: org.hibernate.dialect.Oracle10gDialect
        ddl-auto: none
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
hystrix:
  stream:
    queue:
      enabled: false
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
  threadpool:
    default:
      coreSize: 50
      maximumSize: 300
      allowMaximumSizeToDivergeFromCoreSize: true

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.tour.domain
  type-handlers-package: com.tour.domain
  configuration:
    default-statement-timeout: 3
