-- data insert
INSERT INTO TOUR (PROGRAM_NO, PROGRAM_NAME, THEME, SERVICE_CODE, SERVICE_AREA, PROGRAM_TITLE, PROGRAM_DETAIL)
SELECT CONVERT("PROGRAM_NO", LONG), "PROGRAM_NAME", "THEME", "SERVICE_CODE", "SERVICE_AREA", "PROGRAM_TITLE", "PROGRAM_DETAIL"
FROM csvread('classpath:original-data.csv', 'PROGRAM_NO,PROGRAM_NAME,THEME,SERVICE_CODE,SERVICE_AREA,PROGRAM_TITLE,PROGRAM_DETAIL', NULL );
